kind: Secret
apiVersion: v1
metadata:
  name: devworkspace-container-registry-dockercfg
  labels:
    controller.devfile.io/devworkspace_pullsecret: 'true'
    controller.devfile.io/mount-to-devworkspace: 'true' # this will auto mount to: /etc/secret/devworkspace-container-registry-dockercfg/.dockerconfigjson
    controller.devfile.io/watch-secret: 'true'
data:
  # This is base64 encoded: {"auths":{"somedomain.com":{"username":"somerobotaccount","password":"test123","auth":"c29tZXJvYm90YWNjb3VudDp0ZXN0MTIz","email":""}}}
  # 1. You can get this json info from your registry token , base64 encode it, and update the below
  # 2. Or you can deploy this and modify the specific fields after deployment. <- Recommended
  .dockerconfigjson: eyJhdXRocyI6eyJzb21lZG9tYWluLmNvbSI6eyJ1c2VybmFtZSI6InNvbWVyb2JvdGFjY291bnQiLCJwYXNzd29yZCI6InRlc3QxMjMiLCJhdXRoIjoiYzI5dFpYSnZZbTkwWVdOamIzVnVkRHAwWlhOME1USXoiLCJlbWFpbCI6IiJ9fX0=
type: kubernetes.io/dockerconfigjson
